# Imports e carregamento dos dados

In [3]:
import pandas as pd

df_games = pd.read_csv("games.csv")
display(df_games.head())

,game_id,title,platform,platform_type,platform_maker,platform_generation,genre,year,publisher,developer,...,online_multiplayer,dlc_released,microtransactions,loot_boxes,game_pass_available,vr_support,goty_nominated,goty_won,how_long_to_beat_main_hrs,how_long_to_beat_completionist_hrs
0,G000001,eFootball 2023,Game Boy,Handheld,Nintendo,4,Sports,1990,CD Projekt,Deep Silver,...,1,1,0,0,0,0,0,0,31.8,86.1
1,G000002,Doom 3,Xbox,Console,Microsoft,6,Rhythm,2004,Ubisoft,Ubisoft,...,0,1,1,0,0,0,0,0,13.1,55.4
2,G000003,God of Fire,PC,PC,Various,0,Misc,1988,Microsoft Studios,Microsoft Studios,...,0,0,0,0,0,0,0,0,9.8,20.9
3,G000004,Call of Duty: Rising Sun,Mobile (Android),Mobile,Google,0,Shooter,2017,InXile Entertainment,InXile Entertainment,...,1,1,1,0,0,0,0,0,9.1,44.8
4,G000005,Fortnite 3,Nintendo 64,Console,Nintendo,5,Battle Royale,1999,Naughty Dog,id Software,...,1,0,1,0,0,0,0,0,150.8,322.3

# Inspeção inicial dos dados
Verificando inconsistências na coluna `platform` — identificamos jogos modernos cadastrados no Game Boy com datas e títulos inválidas. Além disso, o dataset possui muitas colunas que não serão utilizadas nesta análise e serão removidas na etapa de limpeza.

In [4]:
# Inspeção
display(df_games.info())
display(df_games.describe())
display(df_games.columns)

df_games[df_games['platform'] == 'Game Boy']
df_games[df_games['platform'] == 'Game Boy'][['title', 'platform', 'year']].sort_values('year', ascending=False).head(20)

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 35 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   game_id                             50000 non-null  str
 1   title                               50000 non-null  str
 2   platform                            50000 non-null  str
 3   platform_type                       50000 non-null  str
 4   platform_maker                      50000 non-null  str
 5   platform_generation                 50000 non-null  int64
 6   genre                               50000 non-null  str
 7   year                                50000 non-null  int64
 8   publisher                           50000 non-null  str
 9   developer                           50000 non-null  str
 10  publisher_region                    50000 non-null  str
 11  publisher_tier                      50000 non-null  str
 12  esrb_rating                         50000 non-null  str
 13  metacritic_score                    50000 non-null  int64
 14  user_score                          50000 non-null  float64
 15  critic_review_count                 50000 non-null  int64
 16  user_review_count                   50000 non-null  int64
 17  na_sales_million                    50000 non-null  float64
 18  eu_sales_million                    50000 non-null  float64
 19  jp_sales_million                    50000 non-null  float64
 20  other_sales_million                 50000 non-null  float64
 21  global_sales_million                50000 non-null  float64
 22  estimated_revenue_million_usd       50000 non-null  float64
 23  launch_price_usd                    50000 non-null  float64
 24  is_sequel                           50000 non-null  int64
 25  online_multiplayer                  50000 non-null  int64
 26  dlc_released                        50000 non-null  int64
 27  microtransactions                   50000 non-null  int64
 28  loot_boxes                          50000 non-null  int64
 29  game_pass_available                 50000 non-null  int64
 30  vr_support                          50000 non-null  int64
 31  goty_nominated                      50000 non-null  int64
 32  goty_won                            50000 non-null  int64
 33  how_long_to_beat_main_hrs           50000 non-null  float64
 34  how_long_to_beat_completionist_hrs  50000 non-null  float64
dtypes: float64(10), int64(14), str(11)
memory usage: 13.4 MB

None

,platform_generation,year,metacritic_score,user_score,critic_review_count,user_review_count,na_sales_million,eu_sales_million,jp_sales_million,other_sales_million,...,online_multiplayer,dlc_released,microtransactions,loot_boxes,game_pass_available,vr_support,goty_nominated,goty_won,how_long_to_beat_main_hrs,how_long_to_beat_completionist_hrs
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,...,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000
mean,4.397120,2007.479640,74.046480,7.407888,27.290160,470.612300,11.946759,7.732016,3.370298,2.985665,...,0.506960,0.623140,0.310980,0.065020,0.036520,0.024420,0.044640,0.006760,24.84839,87.036108
std,3.256757,11.673832,8.626383,1.160381,26.261779,894.567299,20.717035,13.477750,7.439700,5.634561,...,0.499957,0.484604,0.462899,0.246564,0.187582,0.154351,0.206514,0.081942,34.73811,126.802256
min,0.000000,1985.000000,37.000000,2.200000,0.000000,0.000000,0.030000,0.010000,0.000000,0.010000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,2.000000
25%,0.000000,1998.000000,68.000000,6.600000,11.000000,91.000000,2.420000,1.510000,0.400000,0.540000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.00000,29.400000
50%,5.000000,2008.000000,74.000000,7.400000,20.000000,221.000000,5.940000,3.760000,1.210000,1.380000,...,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.20000,46.100000
75%,7.000000,2017.000000,80.000000,8.200000,34.000000,515.000000,13.420000,8.632500,3.330000,3.260000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.10000,85.200000
max,10.000000,2026.000000,99.000000,10.000000,636.000000,39129.000000,769.070000,389.100000,251.210000,300.560000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,377.50000,1685.000000

Index(['game_id', 'title', 'platform', 'platform_type', 'platform_maker',
       'platform_generation', 'genre', 'year', 'publisher', 'developer',
       'publisher_region', 'publisher_tier', 'esrb_rating', 'metacritic_score',
       'user_score', 'critic_review_count', 'user_review_count',
       'na_sales_million', 'eu_sales_million', 'jp_sales_million',
       'other_sales_million', 'global_sales_million',
       'estimated_revenue_million_usd', 'launch_price_usd', 'is_sequel',
       'online_multiplayer', 'dlc_released', 'microtransactions', 'loot_boxes',
       'game_pass_available', 'vr_support', 'goty_nominated', 'goty_won',
       'how_long_to_beat_main_hrs', 'how_long_to_beat_completionist_hrs'],
      dtype='str')

                                   title  platform  year
374        World of Warcraft: The Fallen  Game Boy  2003
23517                     God of Thunder  Game Boy  2003
804                        PGA Tour 2023  Game Boy  2003
879                        Planet Dragon  Game Boy  2003
948               Night in the Awakening  Game Boy  2003
531                   Rise of the Reborn  Game Boy  2003
24481                         The Sims 2  Game Boy  2003
23129                       Doom : Redux  Game Boy  2003
23161                 Forza Motorsport 6  Game Boy  2003
22943                    Dragon Quest VI  Game Boy  2003
25109   The Elder Scrolls XII: Reckoning  Game Boy  2003
25149                  Metal Gear Empire  Game Boy  2003
25367                    Madden NFL 2023  Game Boy  2003
25421                          Dark Saga  Game Boy  2003
22217                 Rise of the Reborn  Game Boy  2003
22386                  Monument Valley 4  Game Boy  2003
25631                        StarCraft 4  Game Boy  2003
26464                       Doom Evolved  Game Boy  2003
1635                   MLB The Show 2024  Game Boy  2003
48955  The Elder Scrolls XVI: Rising Sun  Game Boy  2003

# Limpeza dos dados
Remoção de colunas desnecessárias para esta análise e exclusão de registros inválidos — jogos cadastrados incorretamente na plataforma Game Boy, com títulos e datas incompatíveis com o hardware.

In [13]:
df_gamesAnalise = df_games.drop(columns=["platform_type", 'publisher_region', 'publisher_tier', 'esrb_rating', 'critic_review_count', 'user_review_count', 'is_sequel', 'online_multiplayer', 'dlc_released', 'microtransactions', 'loot_boxes',
       'game_pass_available', 'vr_support', 'goty_nominated', 'goty_won',
       'how_long_to_beat_main_hrs', 'how_long_to_beat_completionist_hrs', 'platform_generation'])

display(df_gamesAnalise.info())
df_gamesAnalise = df_gamesAnalise.drop_duplicates(subset=["game_id"])

df_gamesAnalise[df_gamesAnalise['platform'] == 'Game Boy']
df_gamesAnalise[df_gamesAnalise['platform'] == 'Game Boy'][['title', 'platform', 'year']].sort_values('year', ascending=False).head(20)

df_gamesAnalise_limpo = df_gamesAnalise[df_gamesAnalise['platform'] != 'Game Boy']
df_gamesAnalise_limpo = df_gamesAnalise_limpo.reset_index(drop=True)

display(df_gamesAnalise_limpo)

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   game_id                        50000 non-null  str
 1   title                          50000 non-null  str
 2   platform                       50000 non-null  str
 3   platform_maker                 50000 non-null  str
 4   genre                          50000 non-null  str
 5   year                           50000 non-null  int64
 6   publisher                      50000 non-null  str
 7   developer                      50000 non-null  str
 8   metacritic_score               50000 non-null  int64
 9   user_score                     50000 non-null  float64
 10  na_sales_million               50000 non-null  float64
 11  eu_sales_million               50000 non-null  float64
 12  jp_sales_million               50000 non-null  float64
 13  other_sales_million            50000 non-null  float64
 14  global_sales_million           50000 non-null  float64
 15  estimated_revenue_million_usd  50000 non-null  float64
 16  launch_price_usd               50000 non-null  float64
dtypes: float64(8), int64(2), str(7)
memory usage: 6.5 MB

None

,game_id,title,platform,platform_maker,genre,year,publisher,developer,metacritic_score,user_score,na_sales_million,eu_sales_million,jp_sales_million,other_sales_million,global_sales_million,estimated_revenue_million_usd,launch_price_usd
0,G000002,Doom 3,Xbox,Microsoft,Rhythm,2004,Ubisoft,Ubisoft,78,9.4,52.28,33.72,5.32,12.30,103.62,5056.51,59.99
1,G000003,God of Fire,PC,Various,Misc,1988,Microsoft Studios,Microsoft Studios,76,6.6,2.90,1.48,0.75,0.91,6.04,138.60,59.99
2,G000004,Call of Duty: Rising Sun,Mobile (Android),Google,Shooter,2017,InXile Entertainment,InXile Entertainment,62,7.0,6.76,3.27,0.73,2.34,13.10,36.98,0.00
3,G000005,Fortnite 3,Nintendo 64,Nintendo,Battle Royale,1999,Naughty Dog,id Software,62,5.6,25.12,15.94,7.02,7.71,55.79,2148.24,69.99
4,G000006,Need for Speed: Shadow War,PC,Various,Racing,2003,2K Games,id Software,68,7.1,7.17,6.28,2.01,2.77,18.23,317.90,59.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47888,G049996,NBA 2026,NES,Nintendo,Sports,2002,Warner Bros. Games,Warner Bros. Games,65,7.3,17.66,9.57,1.24,4.45,32.92,1634.86,39.99
47889,G049997,Kirby's Odyssey,GameCube,Nintendo,Platform,2001,Remedy Entertainment,Remedy Entertainment,70,7.3,4.23,3.50,0.32,1.66,9.71,399.49,59.99
47890,G049998,Baldur's Gate 6,Browser,Various,Role-Playing,2014,Naughty Dog,Larian Studios,80,8.1,8.87,4.81,0.99,0.99,15.66,0.00,0.00
47891,G049999,Lost Ark 3,PlayStation 5,Sony,MMORPG,2021,Larian Studios,Larian Studios,70,6.3,2.49,1.57,0.66,0.69,5.41,174.21,59.99
47892,G050000,FIFA 2023,Mobile (iOS),Apple,Sports,2023,Larian Studios,Larian Studios,68,6.5,6.50,3.76,1.29,1.16,12.71,28.37,0.99

In [15]:
publish_mais_lucrativa = df_gamesAnalise_limpo[["publisher","estimated_revenue_million_usd"]].groupby("publisher").sum()
publish_mais_lucrativa = publish_mais_lucrativa.sort_values(by="estimated_revenue_million_usd", ascending=False)
publish_mais_lucrativa = publish_mais_lucrativa.reset_index()

display(publish_mais_lucrativa)

                 publisher  estimated_revenue_million_usd
0                     Sega                     1439908.61
1                 Nintendo                     1438528.42
2         Sony Interactive                     1427761.23
3                   Capcom                     1390636.63
4              Square Enix                     1386604.79
5             Bandai Namco                     1347871.50
6             FromSoftware                     1332296.15
7                   Konami                     1297093.50
8                 2K Games                     1201298.49
9                    Valve                     1181624.79
10              Epic Games                     1181474.20
11             id Software                     1166131.75
12     Activision Blizzard                     1163904.23
13    Take-Two Interactive                     1160741.09
14      Bethesda Softworks                     1159413.55
15              CD Projekt                     1140864.25
16         Insomniac Games                     1135886.28
17                 Ubisoft                     1126401.30
18             Naughty Dog                     1105304.13
19      Warner Bros. Games                     1105093.52
20         Electronic Arts                     1086803.80
21       Microsoft Studios                     1083229.38
22          Rockstar Games                     1082320.24
23                  Bungie                     1057763.19
24  Obsidian Entertainment                      137628.80
25     Focus Entertainment                      134756.06
26    InXile Entertainment                      132955.68
27     Paradox Interactive                      132385.00
28        Devolver Digital                      132166.04
29          Larian Studios                      130992.30
30             Deep Silver                      126797.57
31               505 Games                      126694.00
32             Double Fine                      123662.10
33                  Team17                      122545.60
34              THQ Nordic                      121005.90
35    Remedy Entertainment                      119362.80
36      Klei Entertainment                       34579.43
37        Supergiant Games                       34107.22
38                Toby Fox                       33447.39
39          Unknown Worlds                       32338.18
40                Raw Fury                       32155.78
41            ConcernedApe                       31314.82
42               tinyBuild                       30785.26
43             Motion Twin                       30738.85
44            Coffee Stain                       30615.00
45                   Other                       30589.95
46        Ghost Ship Games                       30275.89
47             Chucklefish                       30200.41
48   Annapurna Interactive                       28172.79
49           Nomada Studio                       27623.23
50            Humble Games                       26947.85

In [ ]:
gener_popular = df_gamesAnalise_limpo[["genre", "na_sales_million", "eu_sales_million", "jp_sales_million"]].groupby("genre").mean()

display(gener_popular)