In [1]:
import pandas as pd

df_games = pd.read_csv("games.csv")
display(df_games.head())

,game_id,title,platform,platform_type,platform_maker,platform_generation,genre,year,publisher,developer,...,online_multiplayer,dlc_released,microtransactions,loot_boxes,game_pass_available,vr_support,goty_nominated,goty_won,how_long_to_beat_main_hrs,how_long_to_beat_completionist_hrs
0,G000001,eFootball 2023,Game Boy,Handheld,Nintendo,4,Sports,1990,CD Projekt,Deep Silver,...,1,1,0,0,0,0,0,0,31.8,86.1
1,G000002,Doom 3,Xbox,Console,Microsoft,6,Rhythm,2004,Ubisoft,Ubisoft,...,0,1,1,0,0,0,0,0,13.1,55.4
2,G000003,God of Fire,PC,PC,Various,0,Misc,1988,Microsoft Studios,Microsoft Studios,...,0,0,0,0,0,0,0,0,9.8,20.9
3,G000004,Call of Duty: Rising Sun,Mobile (Android),Mobile,Google,0,Shooter,2017,InXile Entertainment,InXile Entertainment,...,1,1,1,0,0,0,0,0,9.1,44.8
4,G000005,Fortnite 3,Nintendo 64,Console,Nintendo,5,Battle Royale,1999,Naughty Dog,id Software,...,1,0,1,0,0,0,0,0,150.8,322.3

In [2]:
# Inspeção
display(df_games.info())
display(df_games.describe())
display(df_games.columns)

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 35 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   game_id                             50000 non-null  str
 1   title                               50000 non-null  str
 2   platform                            50000 non-null  str
 3   platform_type                       50000 non-null  str
 4   platform_maker                      50000 non-null  str
 5   platform_generation                 50000 non-null  int64
 6   genre                               50000 non-null  str
 7   year                                50000 non-null  int64
 8   publisher                           50000 non-null  str
 9   developer                           50000 non-null  str
 10  publisher_region                    50000 non-null  str
 11  publisher_tier                      50000 non-null  str
 12  esrb_rating                         50000 non-null  str
 13  metacritic_score                    50000 non-null  int64
 14  user_score                          50000 non-null  float64
 15  critic_review_count                 50000 non-null  int64
 16  user_review_count                   50000 non-null  int64
 17  na_sales_million                    50000 non-null  float64
 18  eu_sales_million                    50000 non-null  float64
 19  jp_sales_million                    50000 non-null  float64
 20  other_sales_million                 50000 non-null  float64
 21  global_sales_million                50000 non-null  float64
 22  estimated_revenue_million_usd       50000 non-null  float64
 23  launch_price_usd                    50000 non-null  float64
 24  is_sequel                           50000 non-null  int64
 25  online_multiplayer                  50000 non-null  int64
 26  dlc_released                        50000 non-null  int64
 27  microtransactions                   50000 non-null  int64
 28  loot_boxes                          50000 non-null  int64
 29  game_pass_available                 50000 non-null  int64
 30  vr_support                          50000 non-null  int64
 31  goty_nominated                      50000 non-null  int64
 32  goty_won                            50000 non-null  int64
 33  how_long_to_beat_main_hrs           50000 non-null  float64
 34  how_long_to_beat_completionist_hrs  50000 non-null  float64
dtypes: float64(10), int64(14), str(11)
memory usage: 13.4 MB

None

,platform_generation,year,metacritic_score,user_score,critic_review_count,user_review_count,na_sales_million,eu_sales_million,jp_sales_million,other_sales_million,...,online_multiplayer,dlc_released,microtransactions,loot_boxes,game_pass_available,vr_support,goty_nominated,goty_won,how_long_to_beat_main_hrs,how_long_to_beat_completionist_hrs
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,...,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000
mean,4.397120,2007.479640,74.046480,7.407888,27.290160,470.612300,11.946759,7.732016,3.370298,2.985665,...,0.506960,0.623140,0.310980,0.065020,0.036520,0.024420,0.044640,0.006760,24.84839,87.036108
std,3.256757,11.673832,8.626383,1.160381,26.261779,894.567299,20.717035,13.477750,7.439700,5.634561,...,0.499957,0.484604,0.462899,0.246564,0.187582,0.154351,0.206514,0.081942,34.73811,126.802256
min,0.000000,1985.000000,37.000000,2.200000,0.000000,0.000000,0.030000,0.010000,0.000000,0.010000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,2.000000
25%,0.000000,1998.000000,68.000000,6.600000,11.000000,91.000000,2.420000,1.510000,0.400000,0.540000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.00000,29.400000
50%,5.000000,2008.000000,74.000000,7.400000,20.000000,221.000000,5.940000,3.760000,1.210000,1.380000,...,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.20000,46.100000
75%,7.000000,2017.000000,80.000000,8.200000,34.000000,515.000000,13.420000,8.632500,3.330000,3.260000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.10000,85.200000
max,10.000000,2026.000000,99.000000,10.000000,636.000000,39129.000000,769.070000,389.100000,251.210000,300.560000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,377.50000,1685.000000

Index(['game_id', 'title', 'platform', 'platform_type', 'platform_maker',
       'platform_generation', 'genre', 'year', 'publisher', 'developer',
       'publisher_region', 'publisher_tier', 'esrb_rating', 'metacritic_score',
       'user_score', 'critic_review_count', 'user_review_count',
       'na_sales_million', 'eu_sales_million', 'jp_sales_million',
       'other_sales_million', 'global_sales_million',
       'estimated_revenue_million_usd', 'launch_price_usd', 'is_sequel',
       'online_multiplayer', 'dlc_released', 'microtransactions', 'loot_boxes',
       'game_pass_available', 'vr_support', 'goty_nominated', 'goty_won',
       'how_long_to_beat_main_hrs', 'how_long_to_beat_completionist_hrs'],
      dtype='str')